### ISSUE TITLE
Read the wiki, I wanted to clear something up:

### ISSUE THREAD

**Issue by whitman-colm** [skilstak/sss-faq#5]
S stands for stable. If I'm working on a new module update, It becomes E (experimental) I'll implement the experimental versions if that works. sorta like MC Snapshots

**Comment by tslnc04** [comment]
OHHH
BTW: Awesome System

On Thu, Dec 17, 2015 at 1:34 PM, Whitman Huntley <notifications@github.com>
wrote:

> S stands for stable. If I'm working on a new module update, It becomes E
> (experimental) I'll implement the experimental versions if that works.
> sorta like MC Snapshots
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skilstak/sss-faq/issues/5>.
>



-- 
Timothy Laskoski
#Comic Sans MS
