### ISSUE TITLE
odd wording on the contribute page.

### ISSUE THREAD

**Issue by whitman-colm** [skilstak/sss-faq#7]
A few things,

* There needs to be a perquisite that a ticket be seen multiple times. We do not want to be accepting FAQ articles for a non-common problem.

* *If you do not follow guidelines, your article will have a far greater chance not to be accepted!* would be better said as "Failure to follow the guidelines above will result in the rejection of your article." because we should have some standard article format.

Thanks! and **please** remind your students to use S3 today.

**Comment by tslnc04** [comment]
https://skilstak.slack.com/files/coderpythonx/F0GJE5Y5T/sss_markdown_article_layout.md
Fixed

**Comment by whitman-colm** [comment]
thanks!
